// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkRecord.Data.Context;

namespace WorkRecord.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkRecord.Model.Entity.Department", b =>
                {
                    b.Property<string>("DeptID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DeptCode")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME")
                        .HasComputedColumnSql("GETDATE()");

                    b.Property<string>("UpdatedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("DeptID");

                    b.ToTable("T_Department");

                    b.HasData(
                        new
                        {
                            DeptID = "127ba6cf-6f64-4a31-90a0-5078c7850fd3",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424",
                            DeptCode = "1001",
                            DeptName = "开发部",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424"
                        },
                        new
                        {
                            DeptID = "87030fb0-fb51-4a6d-934b-19615fba6bd1",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424",
                            DeptCode = "2001",
                            DeptName = "综合管理部",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424"
                        });
                });

            modelBuilder.Entity("WorkRecord.Model.Entity.Role", b =>
                {
                    b.Property<string>("RoleID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDel")
                        .HasColumnType("bit");

                    b.Property<string>("RoleCode")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME")
                        .HasComputedColumnSql("GETDATE()");

                    b.Property<string>("UpdatedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("RoleID");

                    b.ToTable("T_Role");

                    b.HasData(
                        new
                        {
                            RoleID = "6230ae3d-2014-4a8b-81b4-565e2f053423",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424",
                            IsDel = false,
                            RoleCode = "1",
                            RoleName = "系统管理员",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424"
                        },
                        new
                        {
                            RoleID = "b96ea97b-0681-4034-b317-2d0eaf3dfeed",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424",
                            IsDel = false,
                            RoleCode = "2",
                            RoleName = "部门管理员",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424"
                        },
                        new
                        {
                            RoleID = "39b5f16c-5321-4ef9-934d-3bad00e5f640",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424",
                            IsDel = false,
                            RoleCode = "3",
                            RoleName = "普通员工",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424"
                        });
                });

            modelBuilder.Entity("WorkRecord.Model.Entity.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DepartmentID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDel")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("RoleID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME")
                        .HasComputedColumnSql("GETDATE()");

                    b.Property<string>("UpdatedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("UserID");

                    b.ToTable("T_User");

                    b.HasData(
                        new
                        {
                            UserID = "8d19734d-5781-4f54-b31c-4258cf7e3424",
                            Account = "System",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424",
                            DepartmentID = "87030fb0-fb51-4a6d-934b-19615fba6bd1",
                            IsDel = false,
                            Name = "系统管理员",
                            Password = "E10ADC3949BA59ABBE56E057F20F883E",
                            RoleID = "6230ae3d-2014-4a8b-81b4-565e2f053423",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424"
                        },
                        new
                        {
                            UserID = "88ee150f-78aa-4a06-8600-76683207f01c",
                            Account = "admin",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424",
                            DepartmentID = "127ba6cf-6f64-4a31-90a0-5078c7850fd3",
                            IsDel = false,
                            Name = "admin",
                            Password = "E10ADC3949BA59ABBE56E057F20F883E",
                            RoleID = "b96ea97b-0681-4034-b317-2d0eaf3dfeed",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424"
                        },
                        new
                        {
                            UserID = "d05f4164-09ab-4d54-8c0a-70b4ded3e7a5",
                            Account = "张三",
                            CreatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424",
                            DepartmentID = "127ba6cf-6f64-4a31-90a0-5078c7850fd3",
                            IsDel = false,
                            Name = "张三",
                            Password = "E10ADC3949BA59ABBE56E057F20F883E",
                            RoleID = "39b5f16c-5321-4ef9-934d-3bad00e5f640",
                            UpdatedTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedUserId = "8d19734d-5781-4f54-b31c-4258cf7e3424"
                        });
                });

            modelBuilder.Entity("WorkRecord.Model.Entity.WorkItem", b =>
                {
                    b.Property<string>("WorkID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Memos")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DATETIME")
                        .HasComputedColumnSql("GETDATE()");

                    b.Property<string>("UpdatedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("WorkContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkID");

                    b.ToTable("T_WorkItem");
                });
#pragma warning restore 612, 618
        }
    }
}
